// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Elko Sharhadi Eppasa",
            "url": "https://github.com/elkoshar",
            "email": "elko.s.eppasa@mail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/flight/search": {
            "post": {
                "description": "SearchFlight handles request for searching flights",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flight"
                ],
                "summary": "Search Flight",
                "parameters": [
                    {
                        "type": "string",
                        "default": "id",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SearchCriteria"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_elkoshar_bookcabin_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.SearchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_elkoshar_bookcabin_pkg_response.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "msg": {
                    "type": "string",
                    "example": " "
                },
                "status": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_elkoshar_bookcabin_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {},
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_elkoshar_bookcabin_pkg_response.Error"
                },
                "message": {
                    "type": "string"
                },
                "serverTime": {
                    "type": "integer"
                }
            }
        },
        "service.AirlineInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.DurationInfo": {
            "type": "object",
            "properties": {
                "formatted": {
                    "type": "string"
                },
                "total_minutes": {
                    "type": "integer"
                }
            }
        },
        "service.LocationInfo": {
            "type": "object",
            "properties": {
                "airport": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "datetime": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "service.Metadata": {
            "type": "object",
            "properties": {
                "providers_failed": {
                    "type": "integer"
                },
                "providers_queried": {
                    "type": "integer"
                },
                "providers_succeeded": {
                    "type": "integer"
                },
                "search_time_ms": {
                    "type": "integer"
                },
                "total_results": {
                    "type": "integer"
                }
            }
        },
        "service.PriceInfo": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "formatted": {
                    "type": "string"
                }
            }
        },
        "service.SearchCriteria": {
            "type": "object",
            "properties": {
                "cabinClass": {
                    "type": "string"
                },
                "departureDate": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "passengers": {
                    "type": "integer"
                },
                "returnDate": {
                    "type": "string"
                }
            }
        },
        "service.SearchResponse": {
            "type": "object",
            "properties": {
                "flights": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.UnifiedFlight"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/service.Metadata"
                },
                "return_flights": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.UnifiedFlight"
                    }
                },
                "search_criteria": {
                    "$ref": "#/definitions/service.SearchCriteria"
                }
            }
        },
        "service.UnifiedFlight": {
            "type": "object",
            "properties": {
                "airline": {
                    "$ref": "#/definitions/service.AirlineInfo"
                },
                "amenities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "arrival": {
                    "$ref": "#/definitions/service.LocationInfo"
                },
                "available_seats": {
                    "type": "integer"
                },
                "cabin_class": {
                    "type": "string"
                },
                "departure": {
                    "$ref": "#/definitions/service.LocationInfo"
                },
                "duration": {
                    "$ref": "#/definitions/service.DurationInfo"
                },
                "flight_number": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "$ref": "#/definitions/service.PriceInfo"
                },
                "provider": {
                    "type": "string"
                },
                "stops": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/bookcabin",
	Schemes:          []string{},
	Title:            "Flight Search and Aggregation API",
	Description:      "This service is to handle Flight Search and Aggregation API. For more detail, please visit https://github.com/elkoshar/bookcabin",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
